### ISSUE TITLE
The mighty AllCB

### ISSUE THREAD

**Issue by shk33** [arandilopez/feedback#1]
may I use the awesome ALLCB controller in the Second App Challange contest?
or would I get killed and my soul would burn in hell?

**Comment by arandilopez** [comment]
You can use it...

> Use the source Luke

**Comment by shk33** [comment]
No lo usé, Robby Russell se ha decepcionado de mí.

**Comment by arandilopez** [comment]
[[selfie-placeholder-0]]

llllo
